import Image from "next/legacy/image";
import Head from "next/head";
import { AiFillGithub, AiFillLinkedin, } from "react-icons/ai";
import { SiArtstation } from "react-icons/si";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import Project from "@/components/Project/Project";
import certificates from '/assets/certificates/certificates.json';
import first from '@/assets/certificates/images/first.jpeg';
import second from '@/assets/certificates/images/second.jpeg';
import third from '@/assets/certificates/images/third.jpeg';
import fourth from '@/assets/certificates/images/fourth.jpeg';
import fifth from '@/assets/certificates/images/fifth.jpeg';
import sixth from '@/assets/certificates/images/sixth.jpeg';

import airplane from '@/assets/projects/images/airplane.jpg'
import bedroom from '@/assets/projects/images/bedroom.jpg'
import castleGate from '@/assets/projects/images/castleGate.jpg'
import graveyard from '@/assets/projects/images/graveyard.jpg'
import guns from '@/assets/projects/images/guns.jpg'
import guns2 from '@/assets/projects/images/guns2.jpg'
import hall from '@/assets/projects/images/hall.jpg'
import hammers from '@/assets/projects/images/hammers.jpg'
import hauntedHouse from '@/assets/projects/images/hauntedHouse.jpg'
import helicopter from '@/assets/projects/images/helicopter.jpg'
import house from '@/assets/projects/images/house.jpg'
import livingRoom from '@/assets/projects/images/livingRoom.jpg'
import office from '@/assets/projects/images/office.jpg'
import swords from '@/assets/projects/images/swords.jpg'
import weapons from '@/assets/projects/images/weapons.jpg'
import witchRoom from '@/assets/projects/images/witchRoom.jpg'




export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Pragya Tiwari</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Pragya Tiwari
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Web Developer and UX/UI Designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Description
            </p>

            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://pragya7.artstation.com/" target='_blank'>
                <SiArtstation />
              </a>
              <a href="https://github.com/PragyaT26" target='_blank'>
                <AiFillGithub />
              </a>
              <a href="https://www.linkedin.com/in/pragya-tiwari-031872206/" target='_blank'>
                <AiFillLinkedin />
              </a>
            </div>

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" alt='dp' />
            </div>
          </div>
        </section>
        <section>

          {/* //?: Skills and Certificates */}
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Skills and Certificates</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I love to work on <span className="text-teal-500">User Interface</span> of applications, therefore i have developed <span className="text-teal-500">Skills</span> as below
            </p>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p> */}
          </div>
          <div className="lg:flex-col  gap-10">

            <ul className='lg:flex gap-10'>

              <li key={certificates[0]}>
                <div className="flex flex-col shadow-lg p-2 rounded-xl my-10 dark:shadow-lg dark:shadow-slate-500 dark:bg-white flex-1">
                  <Image
                    width={"1200"}
                    height={"700"}
                    src={first}
                  />
                  <h3 className='text-center text-xl'>{certificates[0].name}</h3>
                  <h3 className='text-center text-lg text-green-800'>{certificates[0].duration}</h3>
                  <h3 className='text-center'><a className='underline text-lg decoration-blue-600 text-blue-500' href={certificates[0].link} target='_blank'>Link</a></h3>
                </div>
              </li>

              <li key={certificates[0]}>
                <div className="flex flex-col shadow-lg p-2 rounded-xl my-10 dark:shadow-lg dark:shadow-slate-500 dark:bg-white flex-1">
                  <Image
                    width={"1200"}
                    height={"700"}
                    src={second}
                  />
                  <h3 className='text-center text-xl'>{certificates[1].name}</h3>
                  <h3 className='text-center text-lg text-green-800'>{certificates[1].duration}</h3>
                  <h3 className='text-center'><a className='underline text-lg decoration-blue-600 text-blue-500' href={certificates[1].link} target='_blank'>Link</a></h3>
                </div>
              </li>

              <li key={certificates[2]}>
                <div className="flex flex-col shadow-lg p-2 rounded-xl my-10 dark:shadow-lg dark:shadow-slate-500 dark:bg-white flex-1">
                  <Image
                    width={"1200"}
                    height={"700"}
                    src={third}
                  />
                  <h3 className='text-center text-xl'>{certificates[2].name}</h3>
                  <h3 className='text-center text-lg text-green-800'>{certificates[2].duration}</h3>
                  <h3 className='text-center'><a className='underline text-lg decoration-blue-600 text-blue-500' href={certificates[2].link} target='_blank'>Link</a></h3>
                </div>
              </li>

            </ul>
            <ul className='lg:flex gap-10'>

              <li key={certificates[3]}>
                <div className="flex flex-col shadow-lg p-2 rounded-xl my-10 dark:shadow-lg dark:shadow-slate-500 dark:bg-white flex-1">
                  <Image
                    width={"1200"}
                    height={"700"}
                    src={fourth}
                  />
                  <h3 className='text-center text-xl'>{certificates[3].name}</h3>
                  <h3 className='text-center text-lg text-green-800'>{certificates[3].duration}</h3>
                  <h3 className='text-center'><a className='underline text-lg decoration-blue-600 text-blue-500' href={certificates[3].link} target='_blank'>Link</a></h3>
                </div>
              </li>

              <li key={certificates[4]}>
                <div className="flex flex-col shadow-lg p-2 rounded-xl my-10 dark:shadow-lg dark:shadow-slate-500 dark:bg-white flex-1">
                  <Image
                    width={"1200"}
                    height={"700"}
                    src={fifth}
                  />
                  <h3 className='text-center text-xl'>{certificates[4].name}</h3>
                  <h3 className='text-center text-lg text-green-800'>{certificates[4].duration}</h3>
                  <h3 className='text-center'><a className='underline text-lg decoration-blue-600 text-blue-500' href={certificates[4].link} target='_blank'>Link</a></h3>
                </div>
              </li>

              <li key={certificates[5]}>
                <div className="flex flex-col shadow-lg p-2 rounded-xl my-10 dark:shadow-lg dark:shadow-slate-500 dark:bg-white flex-1">
                  <Image
                    width={"1200"}
                    height={"700"}
                    src={sixth}
                  />
                  <h3 className='text-center text-xl'>{certificates[5].name}</h3>
                  <h3 className='text-center text-lg text-green-800'>{certificates[5].duration}</h3>
                  <h3 className='text-center'><a className='underline text-lg decoration-blue-600 text-blue-500' href={certificates[5].link} target='_blank'>Link</a></h3>
                </div>
              </li>

            </ul>

          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talented people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>

          {/* //?: Projects */}
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <Project image={airplane} />
            <Project image={bedroom} />
            <Project image={castleGate} />
            <Project image={graveyard} />
            <Project image={guns} />
            <Project image={guns2} />
            <Project image={hall} />
            <Project image={hammers} />
            <Project image={hauntedHouse} />
            <Project image={helicopter} />
            <Project image={house} />
            <Project image={livingRoom} />
            <Project image={office} />
            <Project image={swords} />
            <Project image={weapons} />
            <Project image={witchRoom} />
          </div>

        </section>
      </main>
    </div>
  );
}
